import { Field, ObjectType } from 'type-graphql';
import Category from '../category/Category';

@ObjectType()
class Video {
	// Generated by MongoDB
	@Field()
	_id: string;

	@Field()
	name: string;

	@Field()
	description: string;

	@Field()
	category: Category;
}

export default Video;